# Dependencies
markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]

# Permalinks
permalink: pretty
relative_permalinks: false

# Setup
title: Hello
tagline: 'Sayre Photography'
description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec congue fringilla mauris, ac lacinia orci vehicula vel. Donec egestas ante vitae neque vehicula, at tincidunt ante posuere. Ut laoreet, justo.'
url: http://hyde.getpoole.com
baseurl: /

author:
  name: 'Sarah Sayre'
  email: ssayrephotography@outlook.com

paginate: 5

# conditionals
enable_pagination: false
enable_post_date: false
enable_post_links: false
enable_post_related: false
