# Dependencies
markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]

# Permalinks
permalink: pretty
relative_permalinks: false

# Setup
tagline: 'Sayre Photography'
url: https://sarahsayre.com
baseurl: '/'

sidebarLinks:
  - display: 'Contact'
    url: 'mailto:ssayrephotography@outlook.com'
  - display: '@ssayre_photography'
    url: https://www.instagram.com/ssayre_photography

author:
  name: 'Sarah Sayre'
  email: ssayrephotography@outlook.com

paginate: 5

# conditionals
enable_pagination: false
enable_post_date: false
enable_post_links: false
enable_post_related: false
