# Dependencies
markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]

# Permalinks
permalink: pretty
relative_permalinks: false

# Setup
title: Hello
tagline: 'Sayre Photography'
description: 'My name is Sarah and I am a photographer in Southern California.'
url: http://sarahsayre.com
baseurl: /

sidebarLinks:
  - display: '@ssayre_photography'
    url: https://www.instagram.com/ssayre_photography
  - display: '@monochromegrain'
    url: https://www.instagram.com/monochromegrain

author:
  name: 'Sarah Sayre'
  email: ssayrephotography@outlook.com

paginate: 5

# conditionals
enable_pagination: false
enable_post_date: false
enable_post_links: false
enable_post_related: false
